
services:
  app:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: merchai-devcontainer
    volumes:
      - ..:/app
    working_dir: /app
    tty: true
    stdin_open: true
    ports:
      - "8501:8501"
